-- 小兔鲜儿电商数据库初始化脚本
-- 创建数据库
CREATE DATABASE IF NOT EXISTS xtx_shop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE xtx_shop;

-- 用户表
CREATE TABLE IF NOT EXISTS Users (
    Id VARCHAR(32) PRIMARY KEY,
    Account VARCHAR(20) NOT NULL UNIQUE,
    Nickname VARCHAR(50),
    Avatar VARCHAR(255),
    Mobile VARCHAR(20) NOT NULL UNIQUE,
    Gender VARCHAR(10),
    Birthday DATETIME,
    FullLocation VARCHAR(100),
    Profession VARCHAR(50),
    ProvinceCode VARCHAR(20),
    CityCode VARCHAR(20),
    CountyCode VARCHAR(20),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 收货地址表
CREATE TABLE IF NOT EXISTS Addresses (
    Id VARCHAR(32) PRIMARY KEY,
    UserId VARCHAR(32) NOT NULL,
    Receiver VARCHAR(50) NOT NULL,
    Contact VARCHAR(20) NOT NULL,
    ProvinceCode VARCHAR(20) NOT NULL,
    CityCode VARCHAR(20) NOT NULL,
    CountyCode VARCHAR(20) NOT NULL,
    FullLocation VARCHAR(100) NOT NULL,
    AddressDetail VARCHAR(200) NOT NULL,
    IsDefault INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

-- 分类表
CREATE TABLE IF NOT EXISTS Categories (
    Id VARCHAR(32) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Icon VARCHAR(255),
    Picture VARCHAR(255),
    Sort INT DEFAULT 0,
    Level INT DEFAULT 1,
    ParentId VARCHAR(32),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ParentId) REFERENCES Categories(Id) ON DELETE RESTRICT
);

-- 商品表
CREATE TABLE IF NOT EXISTS Goods (
    Id VARCHAR(32) PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    `Description` VARCHAR(500),
    Price DECIMAL(18,2) NOT NULL,
    OldPrice DECIMAL(18,2) NOT NULL,
    MainPicture VARCHAR(255),
    Pictures TEXT,
    Details TEXT,
    Properties TEXT,
    CategoryId VARCHAR(32),
    Inventory INT DEFAULT 0,
    SalesCount INT DEFAULT 0,
    Status INT DEFAULT 1,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE SET NULL
);

-- SKU表
CREATE TABLE IF NOT EXISTS Skus (
    Id VARCHAR(32) PRIMARY KEY,
    GoodsId VARCHAR(32) NOT NULL,
    SkuCode VARCHAR(100) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    OldPrice DECIMAL(18,2) NOT NULL,
    Inventory INT DEFAULT 0,
    Picture VARCHAR(255),
    Specs TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (GoodsId) REFERENCES Goods(Id) ON DELETE CASCADE
);

-- 规格表
CREATE TABLE IF NOT EXISTS Specs (
    Id VARCHAR(32) PRIMARY KEY,
    GoodsId VARCHAR(32) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    `Values` TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (GoodsId) REFERENCES Goods(Id) ON DELETE CASCADE
);

-- 购物车表
CREATE TABLE IF NOT EXISTS CartItems (
    Id VARCHAR(32) PRIMARY KEY,
    UserId VARCHAR(32) NOT NULL,
    SkuId VARCHAR(32) NOT NULL,
    GoodsId VARCHAR(32),
    GoodsName VARCHAR(200),
    Picture VARCHAR(255),
    AttrsText VARCHAR(100),
    Count INT DEFAULT 1,
    Price DECIMAL(18,2) NOT NULL,
    NowPrice DECIMAL(18,2) NOT NULL,
    Stock INT DEFAULT 0,
    Selected TINYINT DEFAULT 1,
    IsEffective TINYINT DEFAULT 1,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (SkuId) REFERENCES Skus(Id) ON DELETE CASCADE
);

-- 订单表
CREATE TABLE IF NOT EXISTS Orders (
    Id VARCHAR(32) PRIMARY KEY,
    UserId VARCHAR(32) NOT NULL,
    OrderState INT DEFAULT 1,
    ReceiverContact VARCHAR(50),
    ReceiverMobile VARCHAR(20),
    ReceiverAddress VARCHAR(200),
    DeliveryTimeType INT DEFAULT 1,
    BuyerMessage VARCHAR(500),
    PayType INT DEFAULT 1,
    PayChannel INT DEFAULT 2,
    TotalMoney DECIMAL(18,2) NOT NULL,
    PostFee DECIMAL(18,2) NOT NULL,
    PayMoney DECIMAL(18,2) NOT NULL,
    PayTime DATETIME,
    ShipTime DATETIME,
    ReceiveTime DATETIME,
    CancelTime DATETIME,
    CancelReason VARCHAR(200),
    CreateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Countdown INT DEFAULT 1800,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

-- 订单商品表
CREATE TABLE IF NOT EXISTS OrderItems (
    Id VARCHAR(32) PRIMARY KEY,
    OrderId VARCHAR(32) NOT NULL,
    SkuId VARCHAR(32) NOT NULL,
    SpuId VARCHAR(32),
    Name VARCHAR(200),
    AttrsText VARCHAR(100),
    Quantity INT DEFAULT 1,
    CurPrice DECIMAL(18,2) NOT NULL,
    Image VARCHAR(255),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE
);

-- 轮播图表
CREATE TABLE IF NOT EXISTS Banners (
    Id VARCHAR(32) PRIMARY KEY,
    ImgUrl VARCHAR(255) NOT NULL,
    HrefUrl VARCHAR(255),
    Type INT DEFAULT 1,
    Sort INT DEFAULT 0,
    Status INT DEFAULT 1,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 热门推荐表
CREATE TABLE IF NOT EXISTS HotRecommends (
    Id VARCHAR(32) PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Alt VARCHAR(200),
    Target VARCHAR(255),
    Pictures TEXT,
    Type VARCHAR(50) NOT NULL,
    Sort INT DEFAULT 0,
    Status INT DEFAULT 1,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 管理员表
CREATE TABLE IF NOT EXISTS AdminUsers (
    Id VARCHAR(32) PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Nickname VARCHAR(50),
    Avatar VARCHAR(255),
    Email VARCHAR(100),
    Status INT DEFAULT 1,
    Role INT DEFAULT 1,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LastLoginAt DATETIME
);

-- 创建索引
CREATE INDEX idx_users_mobile ON Users(Mobile);
CREATE INDEX idx_users_account ON Users(Account);
CREATE INDEX idx_addresses_userid ON Addresses(UserId);
CREATE INDEX idx_cartitems_userid ON CartItems(UserId);
CREATE INDEX idx_orders_userid ON Orders(UserId);
CREATE INDEX idx_orders_state ON Orders(OrderState);
CREATE INDEX idx_goods_category ON Goods(CategoryId);
CREATE INDEX idx_goods_status ON Goods(Status);
CREATE INDEX idx_skus_goodsid ON Skus(GoodsId);
CREATE INDEX idx_specs_goodsid ON Specs(GoodsId);
CREATE INDEX idx_orderitems_orderid ON OrderItems(OrderId);
CREATE INDEX idx_banners_type ON Banners(Type);
CREATE INDEX idx_banners_status ON Banners(Status);
